### ISSUE TITLE
Terminal Colors

### ISSUE THREAD

**Issue by fbcarpinato** [rainglow/vscode#6]
Hi guys, I noticed that in my vscode terminal colors are not affected by themes.
I am currently running the latest version of vscode with Ubuntu 17.10 as OS.

**Comment by daylerees** [comment]
Hi mate. The terminal colors are a fixed set (only the background/foreground colors change for the theme) this is because the terminal colors are meant for a specific purpose (red for error, yellow for info) that kind of thing.

I'm exploring some options for making them fit in a little better, and trying to see whether I can make some iTerm themes to match too.

But don't worry, your theme isn't broken! That's just how its intended for now. :)

**Comment by fbcarpinato** [comment]
> I'm exploring some options for making them fit in a little better, and trying to see whether I can make some iTerm themes to match too

That would be very nice!
